#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
# Enforcing commitizen to run on 'git commit' command is currently disabled
# due to the issue of commitizen running twice when the flow is started with 'git cz'.
# exec < /dev/tty && git cz --hook || true
